{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, api_trans_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.api_pre_approval_req -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.API_PRE_APPROVAL_REQ (transaction load).
--
-- Grain: branch_id, api_trans_id (measured unique over 2,526,543 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 api_trans_id,
 transaction_id,
 transaction_type,
 preauthorisation_id,
 oasis_request_no,
 patient_id,
 episode_no,
 membership_no,
 patient_file_no,
 policy_no,
 member_id_iqama,
 member_name,
 member_mobile_no,
 card_issue_number,
 age,
 gender,
 physician_name,
 provider_code,
 provider_fax_no,
 treatment_type,
 department_type,
 date_of_admission,
 length_of_stay,
 quantity,
 estimated_amount,
 diagnosis_code,
 diagnosis_description,
 chief_complaints_main_symptoms,
 possible_line_of_treatment,
 other_conditions,
 blood_pressure,
 pulse,
 temperature,
 duration_of_illness,
 chronic,
 check_up,
 congenital,
 psychiatric,
 rta,
 infertility,
 work_related,
 vaccination,
 last_menstruation_period,
 process_user,
 verification_id,
 exempted,
 referral,
 ivf_pregnancy,
 normal_pregnancy,
 expected_delivery_date,
 gravida,
 para,
 live,
 abortion,
 death,
 trusted_doctor,
 med_auto_validate_code,
 hospital_id,
 amend_by_user,
 amend_last_date,
 created_by_user,
 creation_date,
 purchaser_code,
 physician_staff_id,
 service_dept,
 attendance_type,
 canceled,
 cancel_message,
 cancel_date,
 canceled_by,
 cancel_api_trans_id,
 treatment_sub_type,
 doctor_specialty_code,
 doctor_dept_code,
 high_blood_pressure,
 low_blood_pressure,
 height,
 weight,
 contract_no,
 policy_code,
 referral_pre_auth_ref,
 referring_provider,
 attached_files,
 new_born,
 doctor_license,
 transfer_request,
 prior_trans_id,
 extend,
 nationality,
 marital_status,
 patient_occupation,
 policy_holder,
 class_code,
 class_value,
 treatment_plan,
 patient_history,
 physical_examination,
 investigation_result,
 oxygen_saturation,
 respiratory_rate,
 maternity,
 attachment_type,
 prescription_auth_ref,
 chief_snomed_code,
 chief_snomed_description,
 history_of_present_illness,
 relative_weight,
 drg_code,
 chief_snomed_dectiption,
 saving_life,
 specialty_doctore_code_referal,
 referal_no,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 merge_hash
from {{ iceberg_source('api_pre_approval_req') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
