{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, bintran_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.bintran -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.BINTRAN (transaction load).
--
-- Grain: branch_id, bintran_id (measured unique over 5,154,555 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 c_id,
 doc_no,
 product_code,
 from_bin,
 to_bin,
 qty,
 status,
 op_code,
 orig_code,
 orig_doc_no,
 tran_date,
 serial_no_1,
 serial_no_2,
 serial_no_3,
 rec_line_id,
 to_c_id,
 qty_allocated,
 update_control_code,
 qty_received,
 transfer_uom_code,
 product_description,
 stocked_indicator,
 stocked_uom,
 job_number,
 control_close_date,
 notes,
 pr_auto_print_flag,
 printed_flag,
 expiry_date,
 unit_price,
 req_status,
 manuf_code,
 manuf_name,
 analysis_code_2,
 product_category_code,
 cost_center,
 work_entity,
 line_id,
 origin_country,
 authorized_by,
 released_by,
 cancel_reason,
 non_stock_desc_id,
 bintran_id,
 posted_date,
 bintran_cross_ref_id,
 ordered_qty,
 cancel_reason_code,
 doc_expiry_date,
 is_tender_pr,
 creation_date,
 authorize_date,
 approve_date,
 cancel_date,
 last_amend_user,
 last_amend_date,
 patient_id,
 qty_canceled,
 is_back_order,
 quot_signed_flag,
 quot_accept_user,
 quot_accept_date,
 print_count,
 price_notes,
 supplier_code,
 quot_post_user,
 qty_on_hand,
 reference_no,
 schedule_id,
 po_qty_on_post,
 pr_qty_on_post,
 quot_post_date,
 is_send,
 committee_record_no,
 committee_record_date,
 lot_no,
 tag_no,
 quot_reject_flag,
 quot_reject_user,
 quot_reject_date,
 trf_posted_by,
 cancelled_by,
 barcode,
 hospital_id,
 bonus,
 bonus_received,
 average_cost,
 tender_id,
 created_by_user,
 authorized_qty,
 released_qty,
 approved_qty,
 quot_auth_flag,
 quot_auth_user,
 quot_auth_date,
 purchase_auth,
 facility_id,
 amend_last_date,
 amend_by_user,
 dir_return_flag,
 dir_return_reason,
 rec_return_committee,
 note_return_committee,
 is_auto_pr,
 is_created_po,
 amu_month,
 quot_rel_flag,
 quot_rel_user,
 quot_rel_date,
 budget_name,
 project_id,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 merge_hash,
 exceed_reason
from {{ iceberg_source('bintran') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
