{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, visit_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.claim_visit_detail -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.CLAIM_VISIT_DETAIL (transaction load).
--
-- Grain: branch_id, visit_id (measured unique over 4,026,835 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 hospital_id,
 visit_id,
 request_date,
 visit_no,
 visit_date,
 visit_type,
 reservation_no,
 referral_ind,
 emergency_indicator,
 emergency_care_level,
 provider_department_code,
 provider_department,
 doctor_specialty_code,
 doctor_specialty,
 doctor_name,
 doctor_code,
 patient_no,
 episode_no,
 patient_name,
 patient_id,
 pilgrim_type,
 birth_country,
 residence_country,
 residence_city,
 religion,
 occupation,
 membership_no,
 main_membership_number,
 patient_relation_code,
 plan_type,
 issue_no,
 patient_id_type,
 patient_national_iqama_id,
 patient_dob,
 patient_age,
 unit_of_age,
 patient_nationality,
 patient_marital_status,
 patient_gender,
 patient_mobile_no,
 patient_badge_no,
 his_insurance_code,
 policy_holder_name,
 policy_holder_no,
 policy_expiry_date,
 class,
 gosi_indicator,
 date_of_accident_injury,
 employer_name,
 employer_registration_number,
 employee_no,
 gosi_insurance_no,
 claim_type,
 admission_date,
 admission_specialty,
 admission_type,
 room_number,
 bed_number,
 discharge_date,
 discharge_specialty,
 length_of_stay,
 admission_weight,
 schs_license_number,
 discharge_mode,
 intended_los,
 er_disposition_code,
 ed_arrival_mode,
 triage_date,
 er_service_start,
 er_waiting_time,
 service_event_type,
 care_type,
 er_major_diagnostic_block,
 condition_onset_flag,
 major_diagnostic_category,
 pccl,
 batch_no,
 total_claimed_amount,
 total_claimed_amount_sar,
 total_net_amount,
 total_discount,
 total_deductible,
 total_patient_vatamount,
 total_net_vat_amount,
 pma_user_id,
 user_name,
 is_fetched,
 user_id_update,
 passport_no,
 user_id_create,
 claim_no,
 doctor_nationality,
 patientid_expirydate,
 eligibility_ref_no,
 referral_no,
 med_rec_no,
 stat_end_date,
 created_by_user,
 creation_date,
 amend_by_user,
 amend_last_date,
 patient_first_name,
 patient_second_name,
 patient_third_name,
 patient_family_name,
 payer_license,
 doctor_license,
 department_type,
 treatment_type,
 claim_invoice_no,
 stat_invoice_no,
 purchaser_code,
 valid,
 validation_message,
 status,
 api_trans_id,
 submit_claim_outcome,
 submit_claim_message,
 surgery_flag,
 submit_by,
 res_transaction_id,
 res_status,
 res_claim_id,
 res_policy_no,
 res_policy_name,
 res_batch_id,
 res_batchtype,
 consultation_invoice_no,
 treatment_sub_type,
 canceled,
 cancel_message,
 cancel_date,
 canceled_by,
 cancel_api_trans_id,
 batch_api_trans_id,
 batch_id,
 eligibility_response_id,
 eligibility_response_system,
 approval_docs,
 contract_no,
 eligibility_api_trans_id,
 eligibility_offline_reference,
 eligibility_offline_date,
 claim_identifier,
 net_with_vat,
 attached_files,
 attachment_type,
 new_born,
 patient_identity_type,
 billable_period_start,
 billable_period_end,
 batch_period_start,
 batch_period_end,
 related_api_trans_id,
 pull_response_id,
 marital_status,
 patient_occupation,
 policy_holder,
 class_code,
 class_value,
 maternity,
 patient_nationality_code,
 relative_weight,
 drg_code,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 etimad,
 auto_rep_attachment,
 auto_trans_attachment,
 merge_hash
from {{ iceberg_source('claim_visit_detail') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
