{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, doc_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.doc -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.DOC (transaction load).
--
-- Grain: branch_id, doc_id (measured unique over 123,148,294 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 c_id,
 doc_date,
 doc_id,
 doc_ind,
 doc_no,
 doc_time,
 doc_type,
 op_code,
 orig_code,
 alloc_doc_id,
 analysis_code_1,
 analysis_category_1,
 analysis_code_2,
 analysis_category_2,
 account_code,
 account_type,
 batch_id,
 client_analysis_code,
 cross_ref_doc_no,
 cross_ref_type,
 currency_code,
 del_add_1,
 del_add_2,
 del_add_3,
 del_add_4,
 del_post_code,
 disc_date,
 doc_disc_percent,
 doc_status,
 due_date,
 exchange_rate,
 exchange_rate_type,
 ext_acc_doc_no,
 fob_code,
 hold_ind,
 job_no,
 last_line_no,
 orig_doc_no,
 payment_terms_code,
 period,
 posted_date,
 reason_code,
 ship_to_code,
 ship_via_code,
 total_doc_cost,
 total_doc_disc,
 total_doc_price,
 tp_seq_no,
 update_control_code,
 unalloc_amount,
 year,
 due_disc,
 payment_amount,
 narrative,
 alloc_batch_id,
 cross_ref_doc_id,
 orig_ref_doc_id,
 gst_exemption_no,
 order_type,
 total_doc_freight,
 total_doc_misc,
 total_doc_tax,
 lc_date,
 printed_ind,
 rev_no,
 exchange_rate_2,
 forex_ref,
 forex_date,
 lc_ref,
 gl_acc,
 gl_stk,
 ext_ref,
 total_lab_cost,
 total_lab_price,
 contract_no,
 orig_disc,
 source_code,
 pod,
 other_code,
 container_code,
 cross_ref_batch_id,
 vehicle_no,
 intac_no,
 container_no,
 vessel_no,
 voyage_no,
 ageing_period,
 transporter_code,
 statement_ind,
 asset_flag,
 payment_card_no,
 total_doc_penalty,
 admin_op_code,
 disc_percentage,
 cancel_flag,
 penalty_period,
 penalty_fixed_val,
 penalty_percent,
 total_doc_bonus,
 priority_code,
 hold_po,
 narrative2,
 download_id,
 rct_rfnd,
 cancel_reason,
 total_doc_vat,
 account_flag,
 vat_register_no,
 direct_purchase_flag,
 trf_no,
 posted_by,
 vat_id,
 committee_record_no,
 committee_record_date,
 payment_batch_id,
 real_posting_date,
 cancel_by,
 cancel_date,
 ref_no,
 authorize_date,
 total_freight_vat,
 hospital_id,
 rfnd_rcpt,
 amend_last_date,
 created_by_user,
 amend_by_user,
 creation_date,
 vat_master_id,
 sub_account_code,
 external_account_code,
 external_invoice_id,
 gl_acc_not,
 old_unalloc_amount,
 project_id,
 gl_batch_id,
 transfere_type,
 used_domain,
 trx_option,
 budget_batch_id,
 doc_vat_code,
 exp_budget_batch_id,
 gl_pck_batch_id,
 facility_id,
 patient_name,
 patient_pobox,
 patient_address,
 rfn_doc_no,
 print_seq,
 nupco_delivery_address,
 nupco_delivery_date,
 adv_unalloc_amount,
 sub_product_category_code,
 take_home,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 merge_hash,
 ap_extra_note,
 ap_note_top,
 invoice_sent,
 invoice_linked_sent
from {{ iceberg_source('doc') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
