{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, line_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.docl -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.DOCL (transaction load).
--
-- Grain: branch_id, line_id (measured unique over 159,794,439 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 c_id,
 doc_no,
 doc_date,
 line_id,
 product_code,
 act_duty_cost,
 act_fob_cost,
 act_ship_cost,
 adj_unit_cost,
 adj_date,
 analysis_code_1,
 analysis_category_1,
 analysis_code_2,
 analysis_category_2,
 analysis_code_3,
 analysis_category_3,
 bin_location,
 dim_uom_code,
 disc_1,
 disc_2,
 doc_type,
 exp_duty_cost,
 exp_fob_cost,
 exp_ship_cost,
 item_dim_1,
 item_dim_2,
 item_dim_3,
 line_no,
 qty_backordered,
 qty_change,
 qty_ordered,
 qty_outstanding,
 qty_rejected,
 qty_shipped,
 rec_date_actual,
 rec_date_promised,
 rec_date_requested,
 serial_no_1,
 serial_no_2,
 serial_no_3,
 ship_date_actual,
 ship_date_promised,
 ship_date_requested,
 unit_cost,
 unit_price,
 doc_status,
 doc_id,
 product_description,
 qty_allocated,
 cross_ref_line_id,
 tax_code,
 cross_ref_doc_id,
 conv_factor,
 line_status,
 new_av_cost,
 list_price,
 list_discount,
 rec_line_id,
 qty_invoice,
 exp_surc_cost,
 act_surc_cost,
 sup_ack_ref,
 sup_ack_date,
 total_cost,
 total_price,
 purc_conv_factor,
 uom_code,
 pick_uom,
 invoice_price,
 qty_pick,
 alt_uom,
 qty_alt,
 insurance_amount,
 tax_rate,
 unit_tax,
 stocked_indicator,
 insp_req,
 insp_status,
 insp_date,
 rej_reason,
 reclaim_tax,
 critical,
 source_code,
 unit_disc,
 type_code,
 discipline,
 equipment,
 standard_cost,
 stock_cid,
 asset_id,
 model_no,
 bonus_order,
 bonus_outstanding,
 origin_country,
 non_stock_desc_id,
 op_code,
 bonus_shipped,
 lot_no,
 gurantee_letter,
 rec_uom,
 cr_qty,
 cr_cert,
 cancel_reason,
 contract_item,
 production_date,
 vat_rate,
 vat_value,
 vat_code,
 new_bin_location,
 manual_vat_entry,
 barcode,
 orig_unit_price,
 hospital_id,
 vat_master_id,
 purchaser_xref_code,
 purchaser_xref_desc,
 orig_unit_cost,
 orig_total_cost,
 amend_last_date,
 created_by_user,
 amend_by_user,
 creation_date,
 rsd_notified,
 rsd_trans_id,
 trx_option,
 budget_batch_id,
 exp_budget_batch_id,
 receipt_alloc_amount,
 receipt_alloc_vat,
 patient_share_type,
 facility_id,
 product_description_a,
 loc_capcity,
 patient_id,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 cost_updated,
 merge_hash
from {{ iceberg_source('docl') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
