{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, account_code, account_type, c_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.external_accounts_data -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: DEVDBA.EXTERNAL_ACCOUNTS_DATA (master load).
--
-- Grain: branch_id, account_code, account_type, c_id (measured unique over 3,886,926 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 account_code,
 account_name,
 c_id,
 organisation_code,
 short_name,
 type,
 add_line_1,
 add_line_2,
 add_line_3,
 add_line_4,
 add_post_code,
 age_break,
 amount_last_receipt,
 amount_last_purchase,
 analysis_category_1,
 analysis_code_1,
 analysis_category_2,
 analysis_code_2,
 analysis_category_3,
 analysis_code_3,
 bank_account_number,
 bank_code,
 bank_sort_code,
 business_sector,
 cleardown_indicator,
 contact_name,
 contact_name_2,
 country,
 credit_terms_code,
 credit_limit,
 credit_limit_2,
 currency_code,
 date_last_purchase,
 date_last_receipt,
 date_last_cr_check,
 date_fin_year_end,
 date_opened,
 expiry_date,
 fax_code,
 fixed_disc,
 gst_exemption_no,
 invoice_to,
 language_ind,
 main_activity,
 organisation_type,
 overdue_interest,
 override_days,
 payee_name,
 payment_method,
 phase_code,
 reg_name,
 reg_add_line_1,
 reg_add_line_2,
 reg_add_line_3,
 reg_add_line_4,
 reg_post_code,
 region_county_state,
 statement_to,
 stopped_ind,
 telephone_number,
 telex_code,
 town_city,
 group_code,
 cg_annexure,
 cg_date,
 cg_file,
 tax_code,
 guarantee_amount,
 last_statement_date,
 account_type,
 pod,
 payment_limit,
 ext_ref,
 charge_type,
 control_code,
 default_delivery_method,
 zone,
 charge_code,
 outstanding_orders,
 outstanding_delnotes,
 bnk_add_line_1,
 bnk_add_line_2,
 bnk_add_line_3,
 bnk_add_line_4,
 bnk_post_code,
 bnk_telephone_no,
 in_episodes_type,
 out_episodes_type,
 black_listed_flag,
 activity_indicator,
 supplier_flag,
 supply_category,
 amend_by_user,
 amend_last_date,
 email_address,
 cr_expire_date,
 activity_indicator_reason,
 black_listed_flag_reason,
 contact_email,
 cr_no,
 cr_start_date,
 contract_start_date,
 contract_end_date,
 vat_cat_type,
 vat_register_no,
 account_end_date,
 created_by_user,
 creation_date,
 hospital_id,
 contract_no,
 use_posting_address,
 rsd_gln,
 extrnal_account_group_id,
 approved_by_user,
 approved_date,
 stop_invoice_to_supplier,
 stop_pay_to_supplier,
 stop_po_to_supplier,
 vat_deferred,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 merge_hash,
 facility_id
from {{ iceberg_source('external_accounts_data') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
