{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, order_line)',
    partition_by='branch_id'
) }}

-- oasis_lake.order_lines -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: OASIS.ORDER_LINES (transaction load).
--
-- Grain: branch_id, order_line (measured unique over 58,414,635 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 order_line,
 master_order_no,
 ios,
 units_ordered,
 units_given,
 auth_outstanding,
 status,
 amend_by_user,
 amend_last_date,
 stock_odoc_line,
 dosage_code,
 dosage_narrative,
 std_price,
 c_id,
 urgent_flag,
 order_work_entity,
 units_scheduled,
 units_completed,
 line_order_date,
 status_reason,
 prefered_staff,
 reason_for_ios,
 original_order_line,
 entity_used_for_qty_calc,
 print_flag,
 created_by_user,
 creation_date,
 line_expiry_date,
 rejected_flag,
 hl7_sent,
 hl7_visit_no,
 initiative_dose,
 generic_id,
 brand_generic_id,
 take_home,
 pacs_accession_no,
 separate_admission_period,
 astm_sent,
 order_by_type,
 chemo_drug_stage,
 customized,
 periodical_checkup,
 re_order_line,
 bb_required_date,
 bb_prev_transfusion_hist,
 bb_prev_trans_reaction,
 bb_order_type,
 ph_hl7_sent,
 consultant_id,
 auto_adjusted,
 adjusted_order_line,
 dhs_transaction_no,
 close_by_staff_id,
 close_by_user,
 close_date,
 close_note,
 last_schedule_datetime,
 first_schedule_datetime,
 acknowledged,
 prn_reason,
 phlblseq,
 answer_session_id,
 batch_no,
 bin_location,
 hospital_id,
 check_list_answers_master_id,
 nurse_review_required,
 vaccine_id,
 lab_acknowledged,
 lab_acknowledge_date,
 trx_sent,
 vaccine_seq,
 ph_reconciliation_line_id,
 extemporaneous,
 ex_order_line,
 pharmacist_review,
 pharmacy_review_by,
 pharmacy_review_date,
 pharmacy_review_note,
 instruction_id,
 detail_answer_session_id,
 auth_type,
 has_absolute_auth,
 back_dated,
 verbal_order,
 verbal_order_ack,
 verbal_order_ack_date,
 conditional_order,
 conditions,
 no_therapeutic_alternative,
 staff_id,
 order_set_id,
 order_set_subitem_id,
 care_plan_id,
 care_plan_item_id,
 pacs_order_schedule_date,
 pacs_order_started_date,
 pacs_order_completed_date,
 dispense_as_written_flag,
 dispense_as_written_reason,
 dispense_as_written_notes,
 bb_bag_order_line,
 onetouch_opr_slot_code,
 of_order_no,
 dispns_win_cd,
 prescription_nphies_verify,
 filler_order_master,
 lab_parent_order_line,
 of_order_source,
 posted_date,
 admin_location,
 dosage_changed,
 dosage_changed_by,
 dosage_changed_date,
 dosage_master_change_seq,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 merge_hash,
 wasfaty_status,
 wasfaty_response,
 wasfaty_entity_id,
 wasfaty_reference_no,
 wasfaty_prescription_id,
 patient_dental_treatment_id,
 nphies_cs_sent
from {{ iceberg_source('order_lines') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
