{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree(recorded_updated_at)',
    order_by='(branch_id, patient_id)',
    partition_by='branch_id'
) }}

-- oasis_lake.patient_master_data -- Oasis Iceberg lake, staged 1:1 into the `oasis` database.
--
-- Source: OASIS.PATIENT_MASTER_DATA (master load).
--
-- Grain: branch_id, patient_id (measured unique over 3,537,038 lake rows)
-- The sorting key IS the dedup key: ReplacingMergeTree collapses on ORDER BY,
-- so every key column is coalesced here (ClickHouse rejects a nullable
-- sorting key, and a nullable version column).
--
-- Incremental: appends rows whose recorded_updated_at -- the dlt load stamp,
-- present on every lake table -- is newer than anything loaded, and
-- ReplacingMergeTree(recorded_updated_at) collapses an older version of a key
-- against the newer one on merge.

select
 patient_id,
 account_no,
 guardian_id,
 pat_name_1,
 pat_name_2,
 pat_name_3,
 pat_family_prefix,
 pat_name_family,
 title,
 religion_code,
 date_of_birth,
 sex,
 nationality_code,
 marital_code,
 occupation_code,
 bad_debt,
 smoker,
 birth_in_hospital,
 date_registered,
 dept_registered,
 soundex_pat_name_1,
 soundex_pat_name_2,
 soundex_pat_name_3,
 soundex_name_family,
 decade_of_birth,
 notes_long_id,
 status,
 new_patient_id,
 amend_by_user,
 amend_last_date,
 image_id,
 mothers_name_1,
 mothers_name_sdx,
 maiden_name,
 maiden_name_sdx,
 maiden_name_prefix,
 registration_type,
 at_risk_flag,
 chronic_flag,
 alert_flag,
 practice_id,
 gp_id,
 security_required,
 scnd_pat_name_1,
 scnd_pat_name_2,
 scnd_pat_name_3,
 scnd_pat_name_family,
 scnd_mothers_name_1,
 scnd_maiden_name,
 scnd_pat_family_prefix,
 scnd_maiden_name_prefix,
 scnd_soundex_pat_name_1,
 scnd_soundex_pat_name_2,
 scnd_soundex_pat_name_3,
 scnd_soundex_name_family,
 scnd_mothers_name_sdx,
 scnd_maiden_name_sdx,
 phone_1,
 phone_2,
 phone_3,
 hight,
 weight,
 temperature,
 high_blood_pressure,
 low_blood_pressure,
 pregnant_start_date,
 pregnant_end_date,
 breast_feeding_start,
 breast_feeding_end,
 abo,
 rh,
 patient_category,
 created_by_user,
 creation_date,
 patient_file_status,
 donor_flag,
 archive_date,
 merged_date,
 merged_by,
 guardian_relation,
 pulse_rate,
 respiratory_rate,
 head_circumference,
 cardiac_rate,
 age_calc_method,
 hl7_sent,
 mobile_no,
 email_address,
 hl7_updated,
 portal_username,
 portal_password,
 portal_verification_code,
 portal_status,
 vip_notes_long_id,
 receive_sms,
 portal_guardian_linked,
 special_need,
 autism,
 hearing,
 dna_blocked_until,
 dna_count,
 healthid,
 plastic_card_prints,
 renal,
 eldery,
 call_center_otp,
 call_center_otp_expiry,
 hospital_id,
 search_text,
 portal_mobile_token,
 coverage_type,
 code_status,
 oasistele_patient_id,
 verify_mobile,
 dnr_added_date,
 dnr_removed_date,
 last_protocol_id,
 last_cycle_seq,
 last_cycle_date,
 code_status_date,
 code_status_by,
 pregnant,
 breast_feeding,
 sexually_active,
 ethnic_group,
 close_emr,
 tawafa_office_name,
 tawafa_office_no,
 disabled,
 oxygen_saturation,
 temperature_site,
 pulse_rate_site,
 respiratory_rate_site,
 blood_pressure_site,
 cardiac_rate_site,
 head_circumference_site,
 oxygen_saturation_site,
 weight_site,
 hight_site,
 temperature_range,
 pulse_rate_range,
 respiratory_rate_range,
 blood_pressure_range,
 cardiac_rate_range,
 head_circumference_range,
 oxygen_saturation_range,
 weight_range,
 hight_range,
 trx_sent,
 trx_update_sent,
 ips_qr_code,
 mmm_update_sent,
 by_integration,
 qr,
 branch_id,
 insert_at,
 ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) as recorded_updated_at,
 temperature_bak,
 mmm_sent,
 rcm_sent,
 rcm_update_sent,
 merge_hash,
 concealed_flag,
 concealed_name,
 mobile_country_code,
 international_mobile_no,
 communication_lang
from {{ iceberg_source('patient_master_data') }}
{% if is_incremental() %}
where ifNull(recorded_updated_at, toDateTime64('1970-01-01 00:00:00', 6)) > (select max(recorded_updated_at) from {{ this }})
{% endif %}
