{#
    ofusion_source(table_name, domain)

    Emits the ClickHouse `icebergLocal(...)` table function for a table in the
    Oracle Fusion Iceberg warehouse, AND registers that table as a dbt source so
    the model shows up with real upstream edges in `dbt docs` lineage.

    The `source()` call below is what does the registration, exactly as in
    `iceberg_source`: dbt captures source()/ref() calls made inside macros while
    parsing the calling model, so a model written as

        from {{ ofusion_source('fact_ap_payment', 'finance') }}

    gets an edge from `ofusion_finance.fact_ap_payment` even though the compiled
    SQL is a table function rather than a relation reference. The return value
    of source() is deliberately discarded -- ClickHouse cannot read the
    warehouse via a plain relation name, only via icebergLocal().

    WHERE THE PATH COMES FROM. Unlike the oasis lake, a Fusion table's path
    cannot be built from its name: the warehouse lays tables out as
    <root>/<domain>/<table>/<run stamp>/, and the stamp is minted per load by a
    pipeline outside this repo. So the path is looked up in ofusion_paths(),
    generated by gui/ofusion_sources.py, which resolves every table to the
    newest stamp directory that actually holds Iceberg metadata.

    A table missing from that lookup fails here, at compile time, with a message
    that says what to do -- rather than at query time with ClickHouse's
    "The metadata file for Iceberg table with path ... doesn't exist".
#}
{% macro ofusion_source(table_name, domain) %}
    {%- set _ = source('ofusion_' ~ domain, table_name) -%}
    {%- set key = domain ~ '.' ~ table_name -%}
    {%- set paths = ofusion_paths() -%}
    {%- if key not in paths -%}
        {{ exceptions.raise_compiler_error(
            "ofusion_source: no Iceberg path known for '" ~ key ~ "'. Either the "
            ~ "table is not in the Fusion warehouse, or its path has not been "
            ~ "resolved yet -- run `python gui/ofusion_sources.py` and try again.") }}
    {%- endif -%}
    icebergLocal('{{ paths[key] }}')
{%- endmacro %}
