{{ config(
    materialized='incremental',
    incremental_strategy='append',
    engine='ReplacingMergeTree()',
    order_by='(branch_id,ios )',
    partition_by='branch_id'
) }}
select 
branch_id,
ios,
service_3,
ios_type,
ios_main,
ios_user,
ios_category,
associate_category,
pharmacy_type,
generic_id,
note_id,
indication_id,
dosage_instruction_id,
special_precaution_id,
interaction_id,
adverse_drug_reaction_id,
inventory_ios,
inventory_price,
orderable_flag,
product_code,
product_category_code,
contraindication_id,
consultant_display_flag,
amend_by_user,
amend_last_date,
no_of_days,
schedul_flag,
reduandant_request_hours,
service_dept,
delivery_price_changeable,
associated_pricing_flag,
procedure_flag,
order_second_approval,
approve_first_order,
reduandant_request_days,
proc_image_details,
auto_delivery_package_items,
blood_product_code,
req_attchment,
insert_at,
recorded_updated_at,
old_ios_user
FROM 
{{ iceberg_source('ios_master_data') }} i
{% if is_incremental() %}
WHERE  i.recorded_updated_at > (SELECT max(recorded_updated_at) FROM {{this}})
{% endif %}